Repository FLAIR-Community/Fling, pull requests merged in 2023-11, with the labels that each got.

#27 feature(whl): add mini-imagenet dataset.
  argzoo/mini_imagenet/mini_imagenet_fedavg_resnet_config.py
  argzoo/mini_imagenet/mini_imagenet_fedper_resnet_config.py
  argzoo/tiny_imagenet/tiny_imagenet_fedavg_resnet_config.py
  argzoo/tiny_imagenet/tiny_imagenet_fedbn_resnet_config.py
  argzoo/tiny_imagenet/tiny_imagenet_fedper_resnet_config.py
  argzoo/tiny_imagenet/tiny_imagenet_fedprox_resnet_config.py
  argzoo/tiny_imagenet/tiny_imagenet_fedrod_resnet_config.py
  argzoo/tiny_imagenet/tiny_imagenet_pfedsd_resnet_config.py
  data/prepare_mini_imagenet.py
  fling/dataset/__init__.py
  fling/dataset/mini_imagenet.py
Labels: enhancement

#28 feature(whl): Add ImageNet dataset.
  data/prepare_mini_imagenet.py
  fling/dataset/__init__.py
  fling/dataset/imagenet.py
  fling/dataset/mini_imagenet.py
  setup.py
Labels: enhancement

#26 feature(gwk): add FedMOON algo
  README.md
  argzoo/cifar10/cifar10_fedmoon_cnn_config.py
  argzoo/cifar100/cifar100_fedmoon_resnet_config.py
  fling/component/client/__init__.py
  fling/component/client/fedmoon_client.py
  fling/model/cnn.py
  fling/model/resnet.py
Labels: algorithm

#30 feature(whl): add lmdb support for imagenet dataset
  data/prepare_imagenet.py
  fling/dataset/imagenet.py
  flzoo/imagenet/imagenet_fedavg_resnet_config.py
  setup.py
Labels: enhancement

#34 fix(whl): polish api for fedmoon
  flzoo/cifar10/cifar10_fedmoon_cnn_config.py
  flzoo/cifar100/cifar100_fedmoon_resnet_config.py
Labels: bug

#35 fix(whl): fix bug for get param
  fling/component/client/base_client.py
  fling/component/group/base_group.py
  fling/utils/__init__.py
  fling/utils/torch_utils.py
Labels: bug
