Repository FLAIR-Community/Fling, pull requests merged in 2023-10, with the labels that each got.

#15 feature(whl): add FedBN algo
  argzoo/cifar10/cifar10_fedbn_resnet_config.py
  argzoo/cifar100/cifar100_fedbn_resnet_config.py
  argzoo/default_config.py
  argzoo/imagenet_tiny/tiny_imagenet_fedbn_resnet_config.py
  fling/cli.py
  fling/component/group/base_group.py
  fling/model/build_model.py
  fling/model/resnet.py
Labels: algorithm

#16 api(whl):update api for finetune
  fling/component/client/base_client.py
  fling/component/client/client_template.py
  fling/component/client/fedprox_client.py
Labels: enhancement

#17 doc(whl):polish readme for fedbn
  README.md
Labels: documentation

#18 feature(whl): add vit model
  fling/model/__init__.py
  fling/model/vit.py
  setup.py
Labels: enhancement

#23 doc(gwk): polish English doc and upload Chinese doc
  docs/cli_en.md
  docs/cli_zh.md
  docs/framework_for_fling_en.md
  docs/framework_for_fling_zh.md
  docs/how_to_add_new_dataset_en.md
  docs/how_to_add_new_dataset_zh.md
  docs/meaning_for_configurations_en.md
  docs/meaning_for_configurations_zh.md
Labels: documentation
